//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeduFirstStep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int AID { get; set; }
        public string ANAME { get; set; }
        public string INFORMATION { get; set; }
        public string LOGINNAME { get; set; }
        public string LOGINPASSWORD { get; set; }
    }
}
